rsyslog:
  image: docker.rodeopartners.com/rsyslog
  volumes:
    - log:/var/log

postfix:
  build: "."
  environment:
    MAIN_MYDESTINATION: ""
    MAIN_MYHOSTNAME: land.fm
    MAIN_MYDOMAIN: land.fm
    USER_CALEB: caleb:gnome
  links:
    - opendkim
    - rsyslog

opendkim:
  image: docker.rodeopartners.com/opendkim
  volumes:
    - keys:/keys
  links:
    - rsyslog
